services:
  # Backend API service
  - type: web
    name: charge-spot-finder-api
    env: node
    runtime: node
    nodeVersion: 18
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  # Frontend static site
  - type: web
    name: charge-spot-finder-frontend
    env: static
    buildCommand: cd frontend && NODE_ENV=production NODE_VERSION=18 npm install && NODE_ENV=production npx --no-install vue-cli-service build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VUE_APP_API_URL
        value: https://charge-spot-finder-api.onrender.com/api
      - key: VUE_APP_MAPBOX_TOKEN
        value: pk.eyJ1IjoiZXZjaGFyZ2luZyIsImEiOiJjbGV3MzRxbTAwMGF6M3ZvNGVnZTlmdjk2In0.0qPcJjJ9QQwFMQR9UoLXjA
